spring.application.name=AllergyService
server.port = 8001

spring.profiles.active=local

service.request.url.prefix = /allergy-service/api/v1

jwt.secret=secret-key
jwt.expiration=3600000

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# -- logger config
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.medibridge.allergy.service.*=INFO
logging.file.name=applogs.log
logging.level.[org.hibernate]=ERROR
logging.level.[com.medibridge.allergy.service.*]=INFO

#--- consul conf
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.instanceId=${spring.application.name}:${server.port}
spring.cloud.consul.discovery.healthCheckInterval=12s
spring.cloud.consul.config.enabled=false